// frontend/momentum-ui/src/app/pages/landing-page/landing-page.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { BrowserStorageService } from '../../services/browser-storage.service';

@Component({
  selector: 'app-landing-page',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './landing-page.component.html',
  styleUrls: ['./landing-page.component.scss'],
})
export class LandingPageComponent {
  @Output() getStarted = new EventEmitter<'single' | 'pair' | 'group'>();
  @Output() login = new EventEmitter<void>();

  constructor(
    private router: Router,
    private storageService: BrowserStorageService
  ) {}

  handleGetStarted(mode: 'single' | 'pair' | 'group') {
    // Store selected mode in localStorage for cross-page state using storage service
    this.storageService.setItem('selectedMode', mode);

    // Use router navigation and also emit event for backward compatibility
    this.router.navigate(['/auth'], { queryParams: { mode } });
    this.getStarted.emit(mode);
  }

  handleLogin() {
    // Use router navigation and also emit event for backward compatibility
    this.router.navigate(['/auth']);
    this.login.emit();
  }

  // Navigate to home page when clicking on the logo/name
  navigateToHome(): void {
    // Since we're already on the landing/home page, we can simply refresh or do nothing
    // For consistency with other components, we'll use the router to navigate to the home route
    this.router.navigate(['/']);
  }
}

<div class="min-h-screen w-full relative overflow-hidden">
  <!-- Background with gradient -->
  <div
    class="absolute inset-0 bg-gradient-to-br from-gray-900 via-black to-gray-800"
  ></div>

  <!-- Background decorative elements -->
  <div
    class="absolute top-20 left-20 w-72 h-72 rounded-full bg-white/5 blur-3xl"
  ></div>
  <div
    class="absolute bottom-20 right-20 w-96 h-96 rounded-full bg-gray-400/10 blur-3xl"
  ></div>
  <div
    class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] rounded-full bg-gray-500/5 blur-3xl"
  ></div>

  <!-- Navigation -->
  <nav class="relative z-10 flex items-center justify-between p-6">
    <div
      class="flex items-center gap-2 cursor-pointer"
      (click)="navigateToHome()"
    >
      <div
        class="w-8 h-8 rounded-lg bg-white/20 backdrop-blur-sm flex items-center justify-center"
      >
        <svg
          class="w-5 h-5 text-white"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M13 10V3L4 14h7v7l9-11h-7z"
          ></path>
        </svg>
      </div>
      <span class="text-white text-xl">Momentum</span>
    </div>

    <div class="hidden md:flex items-center gap-6">
      <a
        href="#features"
        class="text-gray-300 hover:text-white transition-colors"
        >Features</a
      >
      <a
        [routerLink]="['/about']"
        class="text-gray-300 hover:text-white transition-colors"
        >About</a
      >
      <a
        href="#pricing"
        class="text-gray-300 hover:text-white transition-colors"
        >Pricing</a
      >
      <button
        (click)="handleLogin()"
        class="bg-white/10 border border-white/20 text-white hover:bg-white/20 backdrop-blur-sm px-4 py-2 rounded-md transition-colors"
      >
        Login
      </button>
    </div>
  </nav>

  <!-- Hero Section -->
  <div class="relative z-10 max-w-7xl mx-auto px-6 pt-20 pb-32">
    <div class="text-center">
      <div
        class="mb-6 bg-white/10 text-white border border-white/20 backdrop-blur-sm px-3 py-1 rounded-full text-sm inline-block"
      >
        Solo • Pair • Group Tracking
      </div>

      <h1 class="text-5xl md:text-7xl text-white mb-6 tracking-tight">
        Track Your Journey,
        <br />
        <span
          class="bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent"
        >
          Your Way
        </span>
      </h1>

      <p class="text-xl text-gray-300 mb-12 max-w-2xl mx-auto">
        Monitor coding progress, fitness goals, diet, and more. Go solo, pair up
        with a friend, or join a group to stay motivated and achieve your goals
        together.
      </p>

      <!-- CTA Buttons -->
      <div class="flex flex-col sm:flex-row gap-4 justify-center mb-16">
        <button
          (click)="handleGetStarted('single')"
          class="bg-white text-black hover:bg-gray-200 px-8 py-3 text-lg transition-all duration-300 transform hover:scale-105 rounded-md"
        >
          Go Solo
        </button>
        <button
          (click)="handleGetStarted('pair')"
          class="bg-white/10 border border-white/20 text-white hover:bg-white/20 px-8 py-3 text-lg backdrop-blur-sm transition-all duration-300 rounded-md"
        >
          Pair Up
        </button>
        <button
          (click)="handleGetStarted('group')"
          class="bg-white/10 border border-white/20 text-white hover:bg-white/20 px-8 py-3 text-lg backdrop-blur-sm transition-all duration-300 rounded-md"
        >
          Join a Group
        </button>
      </div>

      <!-- Demo Video -->
      <div class="relative max-w-4xl mx-auto">
        <div
          class="backdrop-blur-xl bg-white/10 border border-white/20 rounded-2xl p-2 shadow-2xl"
        >
          <div
            class="relative h-64 md:h-96 bg-gradient-to-br from-gray-800 to-black rounded-xl overflow-hidden cursor-pointer group"
          >
            <div class="absolute inset-0 flex items-center justify-center">
              <div
                class="w-20 h-20 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center group-hover:bg-white/30 transition-colors"
              >
                <svg
                  class="w-8 h-8 text-white ml-1"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path d="M8 5v14l11-7z"></path>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Features Section -->
  <div id="features" class="relative z-10 bg-black/30 backdrop-blur-sm py-24">
    <div class="max-w-7xl mx-auto px-6">
      <h2 class="text-3xl md:text-4xl text-white mb-12 text-center">
        Why Choose Momentum
      </h2>

      <div class="grid md:grid-cols-3 gap-8">
        <div
          class="backdrop-blur-xl bg-white/10 border border-white/20 rounded-xl p-6"
        >
          <div
            class="bg-blue-500/20 text-blue-300 rounded-lg p-3 inline-block mb-4"
          >
            <svg
              class="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
              ></path>
            </svg>
          </div>
          <h3 class="text-xl text-white mb-2">Insightful Analytics</h3>
          <p class="text-gray-300">
            Visualize your progress with detailed charts and insights that help
            you improve.
          </p>
        </div>

        <div
          class="backdrop-blur-xl bg-white/10 border border-white/20 rounded-xl p-6"
        >
          <div
            class="bg-purple-500/20 text-purple-300 rounded-lg p-3 inline-block mb-4"
          >
            <svg
              class="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"
              ></path>
            </svg>
          </div>
          <h3 class="text-xl text-white mb-2">Flexible Collaboration</h3>
          <p class="text-gray-300">
            Work alone or team up with friends to tackle challenges and keep
            each other accountable.
          </p>
        </div>

        <div
          class="backdrop-blur-xl bg-white/10 border border-white/20 rounded-xl p-6"
        >
          <div
            class="bg-green-500/20 text-green-300 rounded-lg p-3 inline-block mb-4"
          >
            <svg
              class="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
              ></path>
            </svg>
          </div>
          <h3 class="text-xl text-white mb-2">Private & Secure</h3>
          <p class="text-gray-300">
            Your data is encrypted and never shared without your explicit
            permission.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

// Classy Glassmorphism Auth Page (1)/components/LandingPage.tsx
"use client";

import { useState } from "react";

type Mode = 'single' | 'pair' | 'group';

interface LandingPageProps {
  onGetStarted: (mode: Mode) => void;
  onLogin: () => void;
}

export function LandingPage({ onGetStarted, onLogin }: LandingPageProps) {
  const [isPlaying, setIsPlaying] = useState(false);

  return (
    <div className="min-h-screen w-full relative overflow-hidden">
      {/* Background with gradient */}
      <div className="absolute inset-0 bg-gradient-to-br from-gray-900 via-black to-gray-800" />
      
      {/* Background decorative elements */}
      <div className="absolute top-20 left-20 w-72 h-72 rounded-full bg-white/5 blur-3xl" />
      <div className="absolute bottom-20 right-20 w-96 h-96 rounded-full bg-gray-400/10 blur-3xl" />
      <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] rounded-full bg-gray-500/5 blur-3xl" />

      {/* Navigation */}
      <nav className="relative z-10 flex items-center justify-between p-6">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-white/20 backdrop-blur-sm flex items-center justify-center">
            <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
          <span className="text-white text-xl">TrackrCollab</span>
        </div>
        
        <div className="hidden md:flex items-center gap-6">
          <a href="#features" className="text-gray-300 hover:text-white transition-colors">Features</a>
          <a href="#about" className="text-gray-300 hover:text-white transition-colors">About</a>
          <a href="#pricing" className="text-gray-300 hover:text-white transition-colors">Pricing</a>
          <button 
            onClick={onLogin}
            className="bg-white/10 border border-white/20 text-white hover:bg-white/20 backdrop-blur-sm px-4 py-2 rounded-md transition-colors"
          >
            Login
          </button>
        </div>
      </nav>

      {/* Hero Section */}
      <div className="relative z-10 max-w-7xl mx-auto px-6 pt-20 pb-32">
        <div className="text-center">
          <div className="mb-6 bg-white/10 text-white border border-white/20 backdrop-blur-sm px-3 py-1 rounded-full text-sm inline-block">
            Solo • Pair • Group Tracking
          </div>
          
          <h1 className="text-5xl md:text-7xl text-white mb-6 tracking-tight">
            Track Your Journey,
            <br />
            <span className="bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent">
              Your Way
            </span>
          </h1>
          
          <p className="text-xl text-gray-300 mb-12 max-w-2xl mx-auto">
            Monitor coding progress, fitness goals, diet, and more. Go solo, pair up with a friend, 
            or join a group to stay motivated and achieve your goals together.
          </p>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
            <button 
              onClick={() => onGetStarted('single')}
              className="bg-white text-black hover:bg-gray-200 px-8 py-3 text-lg transition-all duration-300 transform hover:scale-105 rounded-md"
            >
              Go Solo
            </button>
            <button 
              onClick={() => onGetStarted('pair')}
              className="bg-white/10 border border-white/20 text-white hover:bg-white/20 px-8 py-3 text-lg backdrop-blur-sm transition-all duration-300 rounded-md"
            >
              Pair Up
            </button>
            <button 
              onClick={() => onGetStarted('group')}
              className="bg-white/10 border border-white/20 text-white hover:bg-white/20 px-8 py-3 text-lg backdrop-blur-sm transition-all duration-300 rounded-md"
            >
              Join a Group
            </button>
          </div>

          {/* Demo Video */}
          <div className="relative max-w-4xl mx-auto">
            <div className="backdrop-blur-xl bg-white/10 border border-white/20 rounded-2xl p-2 shadow-2xl">
              <div 
                className="relative h-64 md:h-96 bg-gradient-to-br from-gray-800 to-black rounded-xl overflow-hidden cursor-pointer group"
                onClick={() => setIsPlaying(!isPlaying)}
              >
                <div className="absolute inset-0 flex items-center justify-center">
                  <div className="w-20 h-20 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center group-hover:bg-white/30 transition-colors">
                    <svg className="w-8 h-8 text-white ml-1" fill="currentColor" viewBox="0 0 24 24">
                      <path d="M8 5v14l11-7z" />
                    </svg>
                  </div>
                </div>
                <div className="absolute bottom-4 left-4 text-white">
                  <p className="text-sm opacity-75">30-second demo</p>
                  <p>Dashboard & Heatmap Overview</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div id="features" className="relative z-10 max-w-7xl mx-auto px-6 py-32">
        <div className="text-center mb-16">
          <h2 className="text-4xl text-white mb-4">Everything You Need to Succeed</h2>
          <p className="text-gray-300 text-lg">Comprehensive tracking tools designed for consistency and growth</p>
        </div>

        <div className="grid md:grid-cols-3 gap-8">
          {/* Track Everything */}
          <div className="backdrop-blur-xl bg-white/10 border border-white/20 text-white rounded-lg">
            <div className="p-6">
              <div className="w-12 h-12 rounded-lg bg-blue-500/20 flex items-center justify-center mb-4">
                <svg className="w-6 h-6 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
              </div>
              <h3 className="text-xl mb-2">Track Everything</h3>
              <p className="text-gray-300 mb-4">
                Monitor coding progress, gym workouts, diet, journaling, and custom goals all in one place.
              </p>
              <div className="flex flex-wrap gap-2">
                <span className="bg-blue-500/20 text-blue-300 border border-blue-500/30 px-2 py-1 rounded text-sm flex items-center gap-1">
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                  </svg>
                  Coding
                </span>
                <span className="bg-red-500/20 text-red-300 border border-red-500/30 px-2 py-1 rounded text-sm flex items-center gap-1">
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 14l-7 7m0 0l-7-7m7 7V3" />
                  </svg>
                  Fitness
                </span>
                <span className="bg-green-500/20 text-green-300 border border-green-500/30 px-2 py-1 rounded text-sm flex items-center gap-1">
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9v-9m0-9v9" />
                  </svg>
                  Diet
                </span>
                <span className="bg-purple-500/20 text-purple-300 border border-purple-500/30 px-2 py-1 rounded text-sm flex items-center gap-1">
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                  </svg>
                  Journal
                </span>
              </div>
            </div>
          </div>

          {/* Stay Consistent */}
          <div className="backdrop-blur-xl bg-white/10 border border-white/20 text-white rounded-lg">
            <div className="p-6">
              <div className="w-12 h-12 rounded-lg bg-green-500/20 flex items-center justify-center mb-4">
                <svg className="w-6 h-6 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
              <h3 className="text-xl mb-2">Stay Consistent</h3>
              <p className="text-gray-300 mb-4">
                Visual heatmaps, progress graphs, and AI-powered feedback keep you motivated and on track.
              </p>
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 bg-blue-400 rounded-sm" />
                  <span className="text-sm">Visual heatmaps for consistency</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 bg-green-400 rounded-sm" />
                  <span className="text-sm">AI-powered insights & feedback</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 bg-purple-400 rounded-sm" />
                  <span className="text-sm">Progress tracking & analytics</span>
                </div>
              </div>
            </div>
          </div>

          {/* Connect & Compete */}
          <div className="backdrop-blur-xl bg-white/10 border border-white/20 text-white rounded-lg">
            <div className="p-6">
              <div className="w-12 h-12 rounded-lg bg-orange-500/20 flex items-center justify-center mb-4">
                <svg className="w-6 h-6 text-orange-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                </svg>
              </div>
              <h3 className="text-xl mb-2">Connect & Compete</h3>
              <p className="text-gray-300 mb-4">
                Team up with friends, join groups, compete on leaderboards, and share your journey.
              </p>
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <svg className="w-4 h-4 text-yellow-400" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                  </svg>
                  <span className="text-sm">Group leaderboards</span>
                </div>
                <div className="flex items-center gap-2">
                  <svg className="w-4 h-4 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                  </svg>
                  <span className="text-sm">Real-time group chat</span>
                </div>
                <div className="flex items-center gap-2">
                  <svg className="w-4 h-4 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                  <span className="text-sm">Shared challenges</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="relative z-10 border-t border-white/10 bg-black/20 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-6 py-8">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center gap-2 mb-4 md:mb-0">
              <div className="w-6 h-6 rounded bg-white/20 flex items-center justify-center">
                <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              </div>
              <span className="text-white">TrackrCollab</span>
            </div>
            
            <div className="flex gap-6 text-gray-400">
              <a href="#" className="hover:text-white transition-colors">Privacy Policy</a>
              <a href="#" className="hover:text-white transition-colors">Terms of Service</a>
              <a href="#" className="hover:text-white transition-colors">Contact</a>
              <a href="#" className="hover:text-white transition-colors">GitHub</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
