// frontend/momentum-ui/src/app/app.component.ts
import { Component } from '@angular/core';
import { LandingPageComponent } from './pages/landing-page/landing-page.component';
import { AuthPageComponent } from './Components/app/pages/auth-page/auth-page.component';
import { CommonModule } from '@angular/common';

type AppState = 'landing' | 'auth' | 'mode-selection' | 'dashboard';
type Mode = 'single' | 'pair' | 'group';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    LandingPageComponent,
    AuthPageComponent,
    // ModeSelectionComponent,
    // DashboardComponent,
    // CommonModule,
    CommonModule,
  ],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  currentView: AppState = 'landing';
  selectedMode: Mode = 'single';
  currentSection: string = 'dashboard';

  handleGetStarted(mode: Mode) {
    this.selectedMode = mode;
    this.currentView = 'auth';
  }

  handleLogin() {
    this.currentView = 'auth';
  }

  handleAuthSuccess() {
    this.currentView = 'mode-selection';
  }

  handleModeSelect(mode: Mode) {
    this.selectedMode = mode;
    this.currentView = 'dashboard';
  }

  handleSectionClick(section: string) {
    this.currentSection = section;
    console.log('Navigate to section:', section);
  }
}

<ng-container [ngSwitch]="currentView">

  <app-landing-page
    *ngSwitchCase="'landing'"
    (getStarted)="handleGetStarted($event)"
    (login)="handleLogin()"
  />

  <div *ngSwitchCase="'auth'" class="relative">
    <app-auth-page />

    <!-- Simulated skip to dashboard button -->
    <div class="absolute inset-0 flex items-center justify-center pointer-events-none">
      <button 
        (click)="handleAuthSuccess()"
        class="pointer-events-auto mt-96 text-white/50 hover:text-white text-sm underline"
      >
        Skip to Dashboard (Demo)
      </button>
    </div>
  </div>

  <!-- <app-mode-selection
    *ngSwitchCase="'mode-selection'"
    (modeSelect)="handleModeSelect($event)"
  /> -->

  <!-- <app-dashboard
    *ngSwitchCase="'dashboard'"
    [mode]="selectedMode"
    (sectionClick)="handleSectionClick($event)"
  /> -->

</ng-container>

// Classy Glassmorphism Auth Page (1)/App.tsx
"use client";

import { useState } from "react";
import { LandingPage } from "./components/LandingPage.tsx";
import { AuthPage } from "./components/AuthPage.tsx";
import { ModeSelection } from "./components/ModeSelection.tsx";
import { Dashboard } from "./components/Dashboard.tsx";

type AppState = 'landing' | 'auth' | 'mode-selection' | 'dashboard';
type Mode = 'single' | 'pair' | 'group';

export default function App() {
  const [currentView, setCurrentView] = useState<AppState>('landing');
  const [selectedMode, setSelectedMode] = useState<Mode>('single');
  const [currentSection, setCurrentSection] = useState<string>('dashboard');

  const handleGetStarted = (mode: Mode) => {
    setSelectedMode(mode);
    setCurrentView('auth');
  };

  const handleLogin = () => {
    setCurrentView('auth');
  };

  const handleAuthSuccess = () => {
    setCurrentView('mode-selection');
  };

  const handleModeSelect = (mode: Mode) => {
    setSelectedMode(mode);
    setCurrentView('dashboard');
  };

  const handleSectionClick = (section: string) => {
    setCurrentSection(section);
    // Here you would navigate to specific section components
    console.log('Navigate to section:', section);
  };

  switch (currentView) {
    case 'landing':
      return (
        <LandingPage 
          onGetStarted={handleGetStarted}
          onLogin={handleLogin}
        />
      );
    
    case 'auth':
      return (
        <div className="relative">
          <AuthPage />
          {/* Simulate auth success after 2 seconds for demo */}
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
            <button 
              onClick={handleAuthSuccess}
              className="pointer-events-auto mt-96 text-white/50 hover:text-white text-sm underline"
            >
              Skip to Dashboard (Demo)
            </button>
          </div>
        </div>
      );
    
    case 'mode-selection':
      return (
        <ModeSelection onModeSelect={handleModeSelect} />
      );
    
    case 'dashboard':
      return (
        <Dashboard 
          mode={selectedMode}
          onSectionClick={handleSectionClick}
        />
      );
    
    default:
      return <LandingPage onGetStarted={handleGetStarted} onLogin={handleLogin} />;
  }
}
